---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: blackbox
  namespace: pagetron
  labels:
    app.kubernetes.io/name: blackbox

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox
  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox
    spec:
      containers:
        - name: blackbox
          image: prom/blackbox-exporter:v0.24.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 9115
