---

apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-config
  namespace: pagetron

data:
  prometheus.yml: |
    global:
      scrape_interval: 60s
      scrape_timeout: 10s
      evaluation_interval: 60s

    # rule_files:
    #   - "first_rules.yml"
    #   - "second_rules.yml"

    scrape_configs:
      # self monitoring
      - job_name: prometheus
        metrics_path: "/metrics"
        scheme: "http"
        static_configs:
          - targets:
              - "localhost:9090"

      # blackbox operational metrics
      - job_name: "blackbox_exporter"
        static_configs:
          - targets:
              - blackbox:9115

      # resources
      - job_name: "blackbox"
        metrics_path: /probe
        params:
          module:
            - http_2xx
        static_configs:
          - targets:
            - https://agrrh.com
            - https://getlock.agrrh.com
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox:9115
