---

targets:
  - https://www.docker.com
  - https://kubernetes.io
  - https://svelte.dev
  - https://fastapi.tiangolo.com
  - https://prometheus.io

publicAccess:
  ingress:
    enabled: true

    class: traefik

  s3:
    enabled: true

    secretName: s3-publish-credentials
    bucketName: pagetron-status-page

# May be a good idea to use nip.io and minikube, e.g.:
#   publicUrl: http://pagetron.192-168-42-1.nip.io
# (know your minikube address with `minikube ip` command)
publicUrl: https://pagetron-dev.agrrh.com

timezone: Europe/Moscow

backend:
  replicas: 1

frontend:
  replicas: 1

publisher:
  schedule: "*/1 * * * *"
