{{- with $.Values.backend }}

---

apiVersion: v1
kind: Service

metadata:
  name: pagetron-backend
  labels:
    app: pagetron
    component: backend

spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

  selector:
    app: pagetron
    component: backend

{{- end }}
