{{- with $.Values.housekeeper }}

---

apiVersion: batch/v1
kind: CronJob

metadata:
  name: pagetron-housekeeper
  labels:
    app: pagetron
    component: housekeeper

spec:
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: housekeeper
              image: "{{ .image.repository }}:{{ .image.tag }}"
              imagePullPolicy: IfNotPresent
              command: ["/bin/ash"]
              args:
                - /job/job.sh

              volumeMounts:
                - name: job
                  mountPath: /job

      volumes:
        - name: job
          configMap:
            name: pagetron-housekeeper-job

{{- end }}
