{{- with $.Values.prometheus }}

---

apiVersion: v1
kind: Service

metadata:
  name: prometheus
  labels:
    app: pagetron
    component: prometheus

spec:
  type: ClusterIP

  selector:
    app: pagetron
    component: prometheus

  ports:
    - name: http
      port: 9090
      targetPort: http
      protocol: TCP

{{- end }}
