{{- with $.Values.prometheus }}

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: prometheus
  labels:
    app: pagetron
    component: prometheus

spec:
  strategy:
    type: Recreate
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: pagetron
      component: prometheus

  template:
    metadata:
      labels:
        app: pagetron
        component: prometheus

    spec:
      containers:
        - name: prometheus

          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}

          command:
            - /bin/prometheus
          args:
            - --config.file=/etc/prometheus/prometheus.yaml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
            - --web.enable-lifecycle
            - --web.enable-admin-api
            - --storage.tsdb.retention.time=10y
            - --storage.tsdb.retention.size=10GB

          ports:
            - name: http
              containerPort: 9090
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: http

          readinessProbe:
            httpGet:
              path: /
              port: http

          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus

            {{- range $secret := $.Values.additionalSecrets }}
            - name: secret-{{ $secret }}
              readOnly: true
              mountPath: "/secrets/{{ $secret }}"
            {{- end }}

          resources:
            {{- toYaml .resources | nindent 12 }}

        {{- if .reloader.enabled }}
        - name: reloader

          image: {{ .reloader.image.repository }}:{{ .reloader.image.tag }}
          imagePullPolicy: IfNotPresent

          command:
            - "/configmap-reload"
          args:
            - -volume-dir=/config
            - -webhook-method=POST
            - -webhook-status-code=200
            - -webhook-url=http://127.0.0.1:9090/-/reload
            - -webhook-retries=1

          volumeMounts:
            - name: config
              mountPath: /config

          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 64Mi
        {{- end }}

      volumes:
        - name: config
          configMap:
            name: pagetron-prometheus-config

        - name: data
          persistentVolumeClaim:
            claimName: pagetron-prometheus-data

        {{- range $secret := $.Values.additionalSecrets }}
        - name: secret-{{ $secret }}
          secret:
            secretName: {{ $secret }}
        {{- end }}

      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
