{{- with $.Values.frontend }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: common
  labels:
    app: pagetron
    component: common
  annotations:
    {{- if eq $.Values.ingressClass "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- else if eq $.Values.ingressClass "traefik" }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-backend-strip-prefix@kubernetescrd
    {{- end }}

spec:
  rules:
    - host: {{ $.Values.publicUrl | trimPrefix "https://" | trimPrefix "http://" | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  pagetron-frontend
                port:
                  number: 80
          {{- if eq $.Values.ingressClass "nginx" }}
          - path: /api/(.+)
          {{- else if eq $.Values.ingressClass "traefik" }}
          - path: /api
          {{- end }}
            pathType: Prefix
            backend:
              service:
                name:  pagetron-backend
                port:
                  number: 80

{{- if eq $.Values.ingressClass "traefik" }}
---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware

metadata:
  name: backend-strip-prefix

spec:
  stripPrefixRegex:
    regex:
      - ^/api/?
{{- end }}

{{- end }}
