{{- if $.Values.publicAccess.ingress.enabled }}
{{- with $.Values.frontend }}

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: pagetron-frontend
  labels:
    app: pagetron
    component: frontend

spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: pagetron
      component: frontend

  template:
    metadata:
      labels:
        app: pagetron
        component: frontend

    spec:
      containers:
        - name: pagetron-frontend

          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: http

          readinessProbe:
            httpGet:
              path: /
              port: http

          resources:
            {{- toYaml .resources | nindent 12 }}

      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
{{- end }}
