---

apiVersion: v1
kind: Service

metadata:
  name: blackbox
  namespace: pagetron
  labels:
    app.kubernetes.io/name: blackbox

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: blackbox
  ports:
    - name: http
      port: 9115
      protocol: TCP
      targetPort: http
