---

name: frontend

on:
  # schedule:
  #   - cron: "0 10 * * *"
  push:
    # branches:
    #   - "**"
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches:
  #     - "master"

jobs:
  docker:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta (builder)
        id: meta_builder
        uses: docker/metadata-action@v5
        with:
          images: |
            agrrh/pagetron-frontend-builder
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker meta (static)
        id: meta_static
        uses: docker/metadata-action@v5
        with:
          images: |
            agrrh/pagetron-frontend
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (builder)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          target: builder
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_builder.outputs.tags }}

      - name: Build and push (static)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_static.outputs.tags }}
