---

name: helm chart

on:
  push:
    branches:
      # - master
      - feat/publish-charts

jobs:
  release:
    name: Release Chart

    runs-on: ubuntu-latest

    permissions:
      contents: write

    # container:
    #   image: agrrh/github-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global --add safe.directory "$(pwd)"
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: "${{ secrets.CR_TOKEN }}"

      # https://github.com/marketplace/actions/helm-chart-releaser
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
        with:
          charts_dir: charts/
